import json
from datetime import datetime
from flask import *
from google.cloud import datastore
import calendar

app = Flask(__name__)
DS = datastore.Client()


def _add_event(event):
    """Adding the event to the database.

    :return: The unique ID of the new event.
    :param event:The event need to be added to the database.
    """
    entity = datastore.Entity(key=DS.key('Lab1-event'))
    entity.update({
        'name': event['name'],
        'date': event['date']
    })

    DS.put(entity)
    return entity.id


def _del_event(ID):
    """Delete an event according to its unique ID.

    :param ID:The unique id of target event
    """
    key = DS.key('Lab1-event', int(ID))
    DS.delete(key)


def get_all():
    """Getting all events stored in the database.
    Automatically delete past events.

    :return events: All events stored in the database.
    """
    query = DS.query(kind='Lab1-event')

    events = query.fetch()
    result = []
    for event in events:
        temp = dict(event)
        if temp['date'].timestamp() < datetime.now().timestamp():
            DS.delete(event.key)
            continue
        temp['ID'] = event.id
        result.append(temp)
    return result


def events2json(events):
    """Transfer event objects into JSON format.
    Generate string of date and ETA from the date property.
    Sort events by the ETA.

    :param events: Event objects need to be transfer.
    :return: Json format events.
    """
    events.sort(key=lambda event: event['date'])

    for event in events:
        timestamp = datetime.timestamp(event['date'])
        current = datetime.now().timestamp()
        event['date'] = event['date'].strftime("%m/%d/%Y")
        event['ETA'] = ''
        diff = int(timestamp - current)
        event['ETA'] = ':' + str(diff % 60) + ' left.'
        diff = diff // 60
        event['ETA'] = ':' + str(diff % 60) + event['ETA']
        diff = diff // 60
        event['ETA'] = str(diff) + event['ETA']
    return json.dumps(events)


@app.route('/')
def root():
    """Generate the web page.

    :return: Render template of web page.
    """
    return send_from_directory('templates/', 'index.html')


@app.route('/events')
def send_events():
    """Select all events in database.
    Send them to the client.

    :return: All entities in database in json form.
    """
    events = events2json(get_all())
    return events


@app.route('/event', methods=['POST'])
def add_event():
    """Insert the event into database.
    If the event doesn't have year, insert the next occurrence of a matching date.

    :return: Status Information.
    """
    event = json.loads(request.data)
    if not event['name']:
        abort(make_response('Name cannot be empty!', 400))
    if not event['date']:
        abort(make_response('Date cannot be empty!', 400))
    date = event['date'].split('/')
    for i in range(len(date)):
        try:
            date[i] = int(date[i])
        except ValueError:
            abort(make_response('Date format is wrong!', 400))

    if len(date) != 2 and len(date) != 3:
        abort(make_response('Date format is wrong!', 400))
    if len(date) == 3:
        event['date'] = datetime(date[0], date[1], date[2])
    if len(date) == 2:
        result = None
        cur_time = datetime.now()
        for year in range(cur_time.year, cur_time.year + 8):
            if date[1] not in calendar.monthrange(year, date[0]):
                continue
            temp = datetime(year, date[0], date[1])
            if temp > cur_time:
                result = temp
                break
        if not result:
            abort(make_response('Date does not exist!'))
        event['date'] = result

    new_ID = _add_event(event)

    return json.dumps({'text': 'Success! The unique ID of the new event is ' + str(new_ID)})


@app.route('/event/<event_id>', methods=['DELETE'])
def del_event(event_id):
    """Delete an event according to the unique ID generated by datastore.

    :param event_id: The unique ID of target event.
    :return: Status Infomation.
    """
    _del_event(event_id)

    return json.dumps({'text': 'Success! Target event has been deleted!'})


if __name__ == '__main__':
    app.run(host='127.0.0.1', port=8080, debug=True)
